// Generated by conformance/python/generate_fixtures.py.
// Do not edit by hand.

const fixtureJsonByName = <String, String>{
  'assignment_cases.json': r'''[
    {
        "col_indices": [
            1,
            0,
            2
        ],
        "cost_matrix": [
            [
                4.0,
                1.0,
                3.0
            ],
            [
                2.0,
                0.0,
                5.0
            ],
            [
                3.0,
                2.0,
                2.0
            ]
        ],
        "maximize": false,
        "name": "scipy_doc_square_minimize",
        "row_indices": [
            0,
            1,
            2
        ]
    },
    {
        "col_indices": [
            0,
            1
        ],
        "cost_matrix": [
            [
                1.0,
                2.0
            ],
            [
                3.0,
                4.0
            ],
            [
                5.0,
                6.0
            ]
        ],
        "maximize": false,
        "name": "rectangular_more_rows_minimize",
        "row_indices": [
            0,
            1
        ]
    },
    {
        "col_indices": [
            0,
            1
        ],
        "cost_matrix": [
            [
                1.0,
                2.0,
                3.0
            ],
            [
                4.0,
                5.0,
                6.0
            ]
        ],
        "maximize": false,
        "name": "rectangular_more_cols_minimize",
        "row_indices": [
            0,
            1
        ]
    },
    {
        "col_indices": [
            0,
            2,
            1
        ],
        "cost_matrix": [
            [
                4.0,
                1.0,
                3.0
            ],
            [
                2.0,
                0.0,
                5.0
            ],
            [
                3.0,
                2.0,
                2.0
            ]
        ],
        "maximize": true,
        "name": "square_maximize",
        "row_indices": [
            0,
            1,
            2
        ]
    },
    {
        "col_indices": [
            0,
            1
        ],
        "cost_matrix": [
            [
                1.0,
                1000.0
            ],
            [
                1000.0,
                1.0
            ]
        ],
        "maximize": false,
        "name": "unique_large_differences",
        "row_indices": [
            0,
            1
        ]
    }
]
''',
  'botsort_cases.json': r'''[
    {
        "expected_output_indices": [
            [],
            []
        ],
        "expected_tracker_id": [
            [],
            []
        ],
        "frames": [
            {
                "confidence": [],
                "xyxy": []
            },
            {
                "confidence": [],
                "xyxy": []
            }
        ],
        "name": "empty_frames",
        "params": {
            "enable_cmc": false,
            "minimum_consecutive_frames": 1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                0
            ],
            [
                0
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        20.0,
                        20.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        1.0,
                        0.0,
                        21.0,
                        20.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        2.0,
                        0.0,
                        22.0,
                        20.0
                    ]
                ]
            }
        ],
        "name": "single_object_instant_first_frame",
        "params": {
            "enable_cmc": false,
            "minimum_iou_threshold_first_assoc": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        10.0,
                        10.0,
                        30.0,
                        30.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        11.0,
                        10.0,
                        31.0,
                        30.0
                    ]
                ]
            }
        ],
        "name": "unconfirmed_track_confirms_on_second_frame",
        "params": {
            "enable_cmc": false,
            "instant_first_frame_activation": false,
            "minimum_consecutive_frames": 2,
            "minimum_iou_threshold_unconfirmed_assoc": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                0
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "xyxy": [
                    [
                        10.0,
                        10.0,
                        30.0,
                        30.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "xyxy": [
                    [
                        11.0,
                        10.0,
                        31.0,
                        30.0
                    ]
                ]
            }
        ],
        "name": "missing_confidence_defaults_to_one",
        "params": {
            "enable_cmc": false,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold_first_assoc": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                0
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        50.0,
                        50.0
                    ]
                ]
            },
            {
                "confidence": [
                    0.3
                ],
                "xyxy": [
                    [
                        2.0,
                        2.0,
                        52.0,
                        52.0
                    ]
                ]
            }
        ],
        "name": "low_confidence_second_stage_recovery",
        "params": {
            "enable_cmc": false,
            "high_conf_det_threshold": 0.6,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold_first_assoc": 0.1,
            "minimum_iou_threshold_second_assoc": 0.1,
            "track_activation_threshold": 0.5
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            []
        ],
        "expected_tracker_id": [
            [
                0
            ],
            []
        ],
        "frames": [
            {
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        20.0,
                        20.0
                    ]
                ]
            },
            {
                "confidence": [
                    0.05
                ],
                "xyxy": [
                    [
                        1.0,
                        0.0,
                        21.0,
                        20.0
                    ]
                ]
            }
        ],
        "name": "very_low_confidence_is_discarded",
        "params": {
            "enable_cmc": false,
            "high_conf_det_threshold": 0.6,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold_first_assoc": 0.1,
            "track_activation_threshold": 0.5
        }
    },
    {
        "expected_output_indices": [
            [
                0,
                1
            ],
            [
                1,
                0
            ]
        ],
        "expected_tracker_id": [
            [
                0,
                1
            ],
            [
                0,
                1
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0,
                    1
                ],
                "confidence": [
                    0.95,
                    0.95
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        20.0,
                        20.0
                    ],
                    [
                        100.0,
                        100.0,
                        120.0,
                        120.0
                    ]
                ]
            },
            {
                "class_id": [
                    1,
                    0
                ],
                "confidence": [
                    0.95,
                    0.95
                ],
                "xyxy": [
                    [
                        101.0,
                        100.0,
                        121.0,
                        120.0
                    ],
                    [
                        1.0,
                        0.0,
                        21.0,
                        20.0
                    ]
                ]
            }
        ],
        "name": "two_objects_output_order",
        "params": {
            "enable_cmc": false,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold_first_assoc": 0.1
        }
    }
]
''',
  'bytetrack_cases.json': r'''[
    {
        "expected_output_indices": [
            [],
            []
        ],
        "expected_tracker_id": [
            [],
            []
        ],
        "frames": [
            {
                "confidence": [],
                "xyxy": []
            },
            {
                "confidence": [],
                "xyxy": []
            }
        ],
        "name": "empty_frames",
        "params": {
            "minimum_consecutive_frames": 1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        10.0,
                        10.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        1.0,
                        0.0,
                        11.0,
                        10.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        2.0,
                        0.0,
                        12.0,
                        10.0
                    ]
                ]
            }
        ],
        "name": "single_object_default",
        "params": {
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                -1
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "xyxy": [
                    [
                        10.0,
                        10.0,
                        20.0,
                        20.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "xyxy": [
                    [
                        11.0,
                        10.0,
                        21.0,
                        20.0
                    ]
                ]
            }
        ],
        "name": "missing_confidence_is_low_confidence",
        "params": {
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        50.0,
                        50.0
                    ]
                ]
            },
            {
                "confidence": [
                    0.3
                ],
                "xyxy": [
                    [
                        2.0,
                        2.0,
                        52.0,
                        52.0
                    ]
                ]
            }
        ],
        "name": "low_confidence_second_stage_recovery",
        "params": {
            "high_conf_det_threshold": 0.6,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1,
            "track_activation_threshold": 0.5
        }
    },
    {
        "expected_output_indices": [
            []
        ],
        "expected_tracker_id": [
            []
        ],
        "frames": [
            {
                "confidence": [
                    0.65
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        10.0,
                        10.0
                    ]
                ]
            }
        ],
        "name": "high_below_activation_is_dropped",
        "params": {
            "high_conf_det_threshold": 0.6,
            "minimum_consecutive_frames": 1,
            "track_activation_threshold": 0.7
        }
    },
    {
        "expected_output_indices": [
            [
                0,
                1
            ],
            [
                1,
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1,
                -1
            ],
            [
                0,
                1
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0,
                    1
                ],
                "confidence": [
                    0.95,
                    0.95
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        40.0,
                        40.0
                    ],
                    [
                        100.0,
                        100.0,
                        140.0,
                        140.0
                    ]
                ]
            },
            {
                "class_id": [
                    1,
                    0
                ],
                "confidence": [
                    0.3,
                    0.95
                ],
                "xyxy": [
                    [
                        102.0,
                        100.0,
                        142.0,
                        140.0
                    ],
                    [
                        2.0,
                        0.0,
                        42.0,
                        40.0
                    ]
                ]
            }
        ],
        "name": "mixed_high_low_output_order",
        "params": {
            "high_conf_det_threshold": 0.6,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1,
            "track_activation_threshold": 0.5
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ],
            [],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ],
            [],
            [
                0
            ]
        ],
        "frames": [
            {
                "confidence": [
                    0.95
                ],
                "xyxy": [
                    [
                        50.0,
                        50.0,
                        70.0,
                        70.0
                    ]
                ]
            },
            {
                "confidence": [
                    0.95
                ],
                "xyxy": [
                    [
                        51.0,
                        50.0,
                        71.0,
                        70.0
                    ]
                ]
            },
            {
                "confidence": [],
                "xyxy": []
            },
            {
                "confidence": [
                    0.95
                ],
                "xyxy": [
                    [
                        53.0,
                        50.0,
                        73.0,
                        70.0
                    ]
                ]
            }
        ],
        "name": "confirmed_track_survives_short_gap",
        "params": {
            "lost_track_buffer": 5,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    }
]
''',
  'iou_cases.json': r'''{
    "boxes_a": [
        [
            0.0,
            0.0,
            10.0,
            10.0
        ],
        [
            20.0,
            20.0,
            30.0,
            30.0
        ],
        [
            0.0,
            0.0,
            0.0,
            10.0
        ]
    ],
    "boxes_b": [
        [
            5.0,
            5.0,
            15.0,
            15.0
        ],
        [
            25.0,
            25.0,
            35.0,
            35.0
        ],
        [
            100.0,
            100.0,
            110.0,
            110.0
        ]
    ],
    "iou_matrix": [
        [
            0.1428571492433548,
            0.0,
            0.0
        ],
        [
            0.0,
            0.1428571492433548,
            0.0
        ],
        [
            0.0,
            0.0,
            0.0
        ]
    ]
}
''',
  'kalman_sort_xyxy.json': r'''{
    "initial_bbox": [
        0.0,
        0.0,
        10.0,
        10.0
    ],
    "steps": [
        {
            "predicted_bbox": [
                0.0,
                0.0,
                10.0,
                10.0
            ],
            "state": [
                0.95260663507109,
                0.0,
                10.95260663507109,
                10.0,
                0.47393364928909953,
                0.0,
                0.47393364928909953,
                0.0
            ],
            "update_bbox": [
                1.0,
                0.0,
                11.0,
                10.0
            ]
        },
        {
            "predicted_bbox": [
                1.4265402843601895,
                0.0,
                11.42654028436019,
                10.0
            ],
            "state": [
                1.9314136719192836,
                0.0,
                11.931413671919284,
                10.0,
                0.8741072440766353,
                0.0,
                0.8741072440766353,
                0.0
            ],
            "update_bbox": [
                2.0,
                0.0,
                12.0,
                10.0
            ]
        },
        {
            "predicted_bbox": [
                2.8055209159959187,
                0.0,
                12.805520915995919,
                10.0
            ],
            "state": [
                2.9591875576173905,
                0.7901448240996817,
                12.95918755761739,
                10.790144824099682,
                0.9592815297231392,
                0.4379611621613583,
                0.9592815297231392,
                0.4379611621613583
            ],
            "update_bbox": [
                3.0,
                1.0,
                13.0,
                11.0
            ]
        }
    ]
}
''',
  'manifest.json': r'''{
    "numpy": "2.4.4",
    "policy": {
        "floats": {
            "atol": 1e-07,
            "rtol": 1e-07
        },
        "kalman_state": {
            "atol": 1e-09,
            "rtol": 1e-07
        },
        "tracker_ids": "exact"
    },
    "psutil": "7.2.2",
    "python": "3.14",
    "scipy": "1.17.1",
    "supervision": "0.28.0",
    "trackers": "editable"
}
''',
  'ocsort_cases.json': r'''[
    {
        "expected_output_indices": [
            [],
            []
        ],
        "expected_tracker_id": [
            [],
            []
        ],
        "frames": [
            {
                "confidence": [],
                "xyxy": []
            },
            {
                "confidence": [],
                "xyxy": []
            }
        ],
        "name": "empty_frames",
        "params": {
            "minimum_consecutive_frames": 1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        20.0,
                        20.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        1.0,
                        0.0,
                        21.0,
                        20.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        2.0,
                        0.0,
                        22.0,
                        20.0
                    ]
                ]
            }
        ],
        "name": "single_object_default",
        "params": {
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "xyxy": [
                    [
                        10.0,
                        10.0,
                        30.0,
                        30.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "xyxy": [
                    [
                        11.0,
                        10.0,
                        31.0,
                        30.0
                    ]
                ]
            }
        ],
        "name": "missing_confidence_defaults_to_one",
        "params": {
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0,
                    1
                ],
                "confidence": [
                    0.9,
                    0.2
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        20.0,
                        20.0
                    ],
                    [
                        100.0,
                        100.0,
                        120.0,
                        120.0
                    ]
                ]
            },
            {
                "class_id": [
                    0,
                    1
                ],
                "confidence": [
                    0.9,
                    0.2
                ],
                "xyxy": [
                    [
                        1.0,
                        0.0,
                        21.0,
                        20.0
                    ],
                    [
                        101.0,
                        100.0,
                        121.0,
                        120.0
                    ]
                ]
            }
        ],
        "name": "low_confidence_detection_is_filtered",
        "params": {
            "high_conf_det_threshold": 0.6,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0,
                1
            ],
            [
                1,
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1,
                -1
            ],
            [
                0,
                1
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0,
                    1
                ],
                "confidence": [
                    0.95,
                    0.95
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        20.0,
                        20.0
                    ],
                    [
                        100.0,
                        100.0,
                        120.0,
                        120.0
                    ]
                ]
            },
            {
                "class_id": [
                    1,
                    0
                ],
                "confidence": [
                    0.95,
                    0.95
                ],
                "xyxy": [
                    [
                        101.0,
                        100.0,
                        121.0,
                        120.0
                    ],
                    [
                        1.0,
                        0.0,
                        21.0,
                        20.0
                    ]
                ]
            }
        ],
        "name": "two_objects_output_order",
        "params": {
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_output_indices": [
            [
                0
            ],
            [
                0
            ],
            [],
            [
                0
            ]
        ],
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ],
            [],
            [
                0
            ]
        ],
        "frames": [
            {
                "confidence": [
                    0.95
                ],
                "xyxy": [
                    [
                        50.0,
                        50.0,
                        80.0,
                        80.0
                    ]
                ]
            },
            {
                "confidence": [
                    0.95
                ],
                "xyxy": [
                    [
                        52.0,
                        50.0,
                        82.0,
                        80.0
                    ]
                ]
            },
            {
                "confidence": [],
                "xyxy": []
            },
            {
                "confidence": [
                    0.95
                ],
                "xyxy": [
                    [
                        56.0,
                        50.0,
                        86.0,
                        80.0
                    ]
                ]
            }
        ],
        "name": "ocr_recovers_short_gap",
        "params": {
            "lost_track_buffer": 5,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    }
]
''',
  'sort_cases.json': r'''[
    {
        "expected_tracker_id": [
            [],
            []
        ],
        "frames": [
            {
                "class_id": [],
                "confidence": [],
                "xyxy": []
            },
            {
                "class_id": [],
                "confidence": [],
                "xyxy": []
            }
        ],
        "name": "empty_frames",
        "params": {
            "minimum_consecutive_frames": 1
        }
    },
    {
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        10.0,
                        10.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        1.0,
                        0.0,
                        11.0,
                        10.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        2.0,
                        0.0,
                        12.0,
                        10.0
                    ]
                ]
            }
        ],
        "name": "single_object_minimum_one",
        "params": {
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0
                ],
                "xyxy": [
                    [
                        10.0,
                        10.0,
                        20.0,
                        20.0
                    ]
                ]
            },
            {
                "class_id": [
                    0
                ],
                "xyxy": [
                    [
                        11.0,
                        10.0,
                        21.0,
                        20.0
                    ]
                ]
            }
        ],
        "name": "missing_confidence_defaults_to_one",
        "params": {
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_tracker_id": [
            [
                -1,
                -1
            ],
            [
                0,
                1
            ],
            [
                0,
                1
            ]
        ],
        "frames": [
            {
                "class_id": [
                    0,
                    1
                ],
                "confidence": [
                    0.9,
                    0.95
                ],
                "xyxy": [
                    [
                        0.0,
                        0.0,
                        10.0,
                        10.0
                    ],
                    [
                        100.0,
                        100.0,
                        110.0,
                        110.0
                    ]
                ]
            },
            {
                "class_id": [
                    0,
                    1
                ],
                "confidence": [
                    0.9,
                    0.95
                ],
                "xyxy": [
                    [
                        1.0,
                        0.0,
                        11.0,
                        10.0
                    ],
                    [
                        101.0,
                        100.0,
                        111.0,
                        110.0
                    ]
                ]
            },
            {
                "class_id": [
                    0,
                    1
                ],
                "confidence": [
                    0.9,
                    0.95
                ],
                "xyxy": [
                    [
                        2.0,
                        0.0,
                        12.0,
                        10.0
                    ],
                    [
                        102.0,
                        100.0,
                        112.0,
                        110.0
                    ]
                ]
            }
        ],
        "name": "two_objects_minimum_two",
        "params": {
            "minimum_consecutive_frames": 2,
            "minimum_iou_threshold": 0.1
        }
    },
    {
        "expected_tracker_id": [
            [
                -1
            ],
            [
                0
            ],
            [],
            [
                0
            ]
        ],
        "frames": [
            {
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        50.0,
                        50.0,
                        60.0,
                        60.0
                    ]
                ]
            },
            {
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        51.0,
                        50.0,
                        61.0,
                        60.0
                    ]
                ]
            },
            {
                "confidence": [],
                "xyxy": []
            },
            {
                "confidence": [
                    0.9
                ],
                "xyxy": [
                    [
                        53.0,
                        50.0,
                        63.0,
                        60.0
                    ]
                ]
            }
        ],
        "name": "short_gap_keeps_identity",
        "params": {
            "lost_track_buffer": 3,
            "minimum_consecutive_frames": 1,
            "minimum_iou_threshold": 0.1
        }
    }
]
''',
};
