# ------------------------------------------------------------------------
# Trackers
# Copyright (c) 2026 Roboflow. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 [see LICENSE for details]
# ------------------------------------------------------------------------

import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import psutil
import scipy
import supervision as sv
from scipy.optimize import linear_sum_assignment
from trackers import BoTSORTTracker, ByteTrackTracker, OCSORTTracker, SORTTracker
from trackers.core.sort.tracklet import SORTTracklet
from trackers.utils.state_representations import XYXYStateEstimator

FIXTURE_DIR = Path(__file__).resolve().parents[1] / "fixtures"
DART_TEST_DIR = Path(__file__).resolve().parents[2] / "test"


def _write(name: str, value: Any) -> None:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    (FIXTURE_DIR / name).write_text(json.dumps(value, indent=4, sort_keys=True) + "\n")


def _write_dart_fixture_library() -> None:
    DART_TEST_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    for path in sorted(FIXTURE_DIR.glob("*.json")):
        entries.append(f"  {path.name!r}: r'''{path.read_text()}''',")
    content = "\n".join(
        [
            "// Generated by conformance/python/generate_fixtures.py.",
            "// Do not edit by hand.",
            "",
            "const fixtureJsonByName = <String, String>{",
            *entries,
            "};",
            "",
        ]
    )
    (DART_TEST_DIR / "fixtures.g.dart").write_text(content)


def _detections(frame: dict[str, Any]) -> sv.Detections:
    xyxy = np.asarray(frame["xyxy"], dtype=np.float64).reshape((-1, 4))
    confidence = frame.get("confidence")
    class_id = frame.get("class_id")
    return sv.Detections(
        xyxy=xyxy,
        confidence=None if confidence is None else np.asarray(confidence, dtype=np.float64),
        class_id=None if class_id is None else np.asarray(class_id, dtype=int),
    )


def generate_assignment_cases() -> None:
    cases: list[dict[str, Any]] = [
        {
            "name": "scipy_doc_square_minimize",
            "cost_matrix": [[4.0, 1.0, 3.0], [2.0, 0.0, 5.0], [3.0, 2.0, 2.0]],
            "maximize": False,
        },
        {
            "name": "rectangular_more_rows_minimize",
            "cost_matrix": [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]],
            "maximize": False,
        },
        {
            "name": "rectangular_more_cols_minimize",
            "cost_matrix": [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]],
            "maximize": False,
        },
        {
            "name": "square_maximize",
            "cost_matrix": [[4.0, 1.0, 3.0], [2.0, 0.0, 5.0], [3.0, 2.0, 2.0]],
            "maximize": True,
        },
        {
            "name": "unique_large_differences",
            "cost_matrix": [[1.0, 1000.0], [1000.0, 1.0]],
            "maximize": False,
        },
    ]
    for case in cases:
        matrix = np.asarray(case["cost_matrix"], dtype=np.float64)
        rows, cols = linear_sum_assignment(matrix, maximize=case["maximize"])
        case["row_indices"] = rows.astype(int).tolist()
        case["col_indices"] = cols.astype(int).tolist()
    _write("assignment_cases.json", cases)


def generate_iou_cases() -> None:
    boxes_a = np.asarray([[0, 0, 10, 10], [20, 20, 30, 30], [0, 0, 0, 10]], dtype=np.float64)
    boxes_b = np.asarray([[5, 5, 15, 15], [25, 25, 35, 35], [100, 100, 110, 110]], dtype=np.float64)
    matrix = sv.box_iou_batch(boxes_a, boxes_b)
    _write(
        "iou_cases.json",
        {
            "boxes_a": boxes_a.tolist(),
            "boxes_b": boxes_b.tolist(),
            "iou_matrix": matrix.astype(float).tolist(),
        },
    )


def generate_kalman_case() -> None:
    initial = np.asarray([0.0, 0.0, 10.0, 10.0], dtype=np.float64)
    tracklet = SORTTracklet(initial, state_estimator_class=XYXYStateEstimator)
    steps = []
    for update_bbox in [
        [1.0, 0.0, 11.0, 10.0],
        [2.0, 0.0, 12.0, 10.0],
        [3.0, 1.0, 13.0, 11.0],
    ]:
        predicted = tracklet.predict()
        tracklet.update(np.asarray(update_bbox, dtype=np.float64))
        steps.append(
            {
                "predicted_bbox": np.asarray(predicted, dtype=np.float64).tolist(),
                "update_bbox": update_bbox,
                "state": tracklet.state_estimator.kf.x.reshape(-1).astype(float).tolist(),
            }
        )
    _write("kalman_sort_xyxy.json", {"initial_bbox": initial.tolist(), "steps": steps})


def generate_sort_cases() -> None:
    cases: list[dict[str, Any]] = [
        {
            "name": "empty_frames",
            "params": {"minimum_consecutive_frames": 1},
            "frames": [{"xyxy": [], "confidence": [], "class_id": []}, {"xyxy": [], "confidence": [], "class_id": []}],
        },
        {
            "name": "single_object_minimum_one",
            "params": {"minimum_consecutive_frames": 1, "minimum_iou_threshold": 0.1},
            "frames": [
                {"xyxy": [[0.0, 0.0, 10.0, 10.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[1.0, 0.0, 11.0, 10.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[2.0, 0.0, 12.0, 10.0]], "confidence": [0.9], "class_id": [0]},
            ],
        },
        {
            "name": "missing_confidence_defaults_to_one",
            "params": {"minimum_consecutive_frames": 1, "minimum_iou_threshold": 0.1},
            "frames": [
                {"xyxy": [[10.0, 10.0, 20.0, 20.0]], "class_id": [0]},
                {"xyxy": [[11.0, 10.0, 21.0, 20.0]], "class_id": [0]},
            ],
        },
        {
            "name": "two_objects_minimum_two",
            "params": {"minimum_consecutive_frames": 2, "minimum_iou_threshold": 0.1},
            "frames": [
                {
                    "xyxy": [[0.0, 0.0, 10.0, 10.0], [100.0, 100.0, 110.0, 110.0]],
                    "confidence": [0.9, 0.95],
                    "class_id": [0, 1],
                },
                {
                    "xyxy": [[1.0, 0.0, 11.0, 10.0], [101.0, 100.0, 111.0, 110.0]],
                    "confidence": [0.9, 0.95],
                    "class_id": [0, 1],
                },
                {
                    "xyxy": [[2.0, 0.0, 12.0, 10.0], [102.0, 100.0, 112.0, 110.0]],
                    "confidence": [0.9, 0.95],
                    "class_id": [0, 1],
                },
            ],
        },
        {
            "name": "short_gap_keeps_identity",
            "params": {"minimum_consecutive_frames": 1, "minimum_iou_threshold": 0.1, "lost_track_buffer": 3},
            "frames": [
                {"xyxy": [[50.0, 50.0, 60.0, 60.0]], "confidence": [0.9]},
                {"xyxy": [[51.0, 50.0, 61.0, 60.0]], "confidence": [0.9]},
                {"xyxy": [], "confidence": []},
                {"xyxy": [[53.0, 50.0, 63.0, 60.0]], "confidence": [0.9]},
            ],
        },
    ]

    for case in cases:
        tracker = SORTTracker(**case["params"])
        tracker.reset()
        expected = []
        for frame in case["frames"]:
            result = tracker.update(_detections(frame))
            expected.append([] if result.tracker_id is None else result.tracker_id.astype(int).tolist())
        case["expected_tracker_id"] = expected
    _write("sort_cases.json", cases)


def _output_indices(frame: dict[str, Any], result: sv.Detections) -> list[int]:
    source_boxes = np.asarray(frame["xyxy"], dtype=np.float64).reshape((-1, 4))
    used: set[int] = set()
    indices: list[int] = []
    for box in result.xyxy:
        candidates = np.where(np.all(np.isclose(source_boxes, box, atol=1e-9), axis=1))[0]
        for candidate in candidates:
            idx = int(candidate)
            if idx not in used:
                used.add(idx)
                indices.append(idx)
                break
        else:
            raise AssertionError(f"Could not map output box {box.tolist()} to input frame {frame}")
    return indices


def generate_bytetrack_cases() -> None:
    cases: list[dict[str, Any]] = [
        {
            "name": "empty_frames",
            "params": {"minimum_consecutive_frames": 1},
            "frames": [{"xyxy": [], "confidence": []}, {"xyxy": [], "confidence": []}],
        },
        {
            "name": "single_object_default",
            "params": {"minimum_iou_threshold": 0.1},
            "frames": [
                {"xyxy": [[0.0, 0.0, 10.0, 10.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[1.0, 0.0, 11.0, 10.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[2.0, 0.0, 12.0, 10.0]], "confidence": [0.9], "class_id": [0]},
            ],
        },
        {
            "name": "missing_confidence_is_low_confidence",
            "params": {"minimum_consecutive_frames": 1, "minimum_iou_threshold": 0.1},
            "frames": [
                {"xyxy": [[10.0, 10.0, 20.0, 20.0]], "class_id": [0]},
                {"xyxy": [[11.0, 10.0, 21.0, 20.0]], "class_id": [0]},
            ],
        },
        {
            "name": "low_confidence_second_stage_recovery",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold": 0.1,
                "track_activation_threshold": 0.5,
                "high_conf_det_threshold": 0.6,
            },
            "frames": [
                {"xyxy": [[0.0, 0.0, 50.0, 50.0]], "confidence": [0.9]},
                {"xyxy": [[2.0, 2.0, 52.0, 52.0]], "confidence": [0.3]},
            ],
        },
        {
            "name": "high_below_activation_is_dropped",
            "params": {
                "minimum_consecutive_frames": 1,
                "track_activation_threshold": 0.7,
                "high_conf_det_threshold": 0.6,
            },
            "frames": [
                {"xyxy": [[0.0, 0.0, 10.0, 10.0]], "confidence": [0.65]},
            ],
        },
        {
            "name": "mixed_high_low_output_order",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold": 0.1,
                "track_activation_threshold": 0.5,
                "high_conf_det_threshold": 0.6,
            },
            "frames": [
                {
                    "xyxy": [[0.0, 0.0, 40.0, 40.0], [100.0, 100.0, 140.0, 140.0]],
                    "confidence": [0.95, 0.95],
                    "class_id": [0, 1],
                },
                {
                    "xyxy": [[102.0, 100.0, 142.0, 140.0], [2.0, 0.0, 42.0, 40.0]],
                    "confidence": [0.3, 0.95],
                    "class_id": [1, 0],
                },
            ],
        },
        {
            "name": "confirmed_track_survives_short_gap",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold": 0.1,
                "lost_track_buffer": 5,
            },
            "frames": [
                {"xyxy": [[50.0, 50.0, 70.0, 70.0]], "confidence": [0.95]},
                {"xyxy": [[51.0, 50.0, 71.0, 70.0]], "confidence": [0.95]},
                {"xyxy": [], "confidence": []},
                {"xyxy": [[53.0, 50.0, 73.0, 70.0]], "confidence": [0.95]},
            ],
        },
    ]

    for case in cases:
        tracker = ByteTrackTracker(**case["params"])
        tracker.reset()
        expected_ids = []
        expected_indices = []
        for frame in case["frames"]:
            result = tracker.update(_detections(frame))
            expected_ids.append([] if result.tracker_id is None else result.tracker_id.astype(int).tolist())
            expected_indices.append(_output_indices(frame, result))
        case["expected_tracker_id"] = expected_ids
        case["expected_output_indices"] = expected_indices
    _write("bytetrack_cases.json", cases)


def generate_ocsort_cases() -> None:
    cases: list[dict[str, Any]] = [
        {
            "name": "empty_frames",
            "params": {"minimum_consecutive_frames": 1},
            "frames": [{"xyxy": [], "confidence": []}, {"xyxy": [], "confidence": []}],
        },
        {
            "name": "single_object_default",
            "params": {"minimum_iou_threshold": 0.1},
            "frames": [
                {"xyxy": [[0.0, 0.0, 20.0, 20.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[1.0, 0.0, 21.0, 20.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[2.0, 0.0, 22.0, 20.0]], "confidence": [0.9], "class_id": [0]},
            ],
        },
        {
            "name": "missing_confidence_defaults_to_one",
            "params": {"minimum_consecutive_frames": 1, "minimum_iou_threshold": 0.1},
            "frames": [
                {"xyxy": [[10.0, 10.0, 30.0, 30.0]], "class_id": [0]},
                {"xyxy": [[11.0, 10.0, 31.0, 30.0]], "class_id": [0]},
            ],
        },
        {
            "name": "low_confidence_detection_is_filtered",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold": 0.1,
                "high_conf_det_threshold": 0.6,
            },
            "frames": [
                {
                    "xyxy": [[0.0, 0.0, 20.0, 20.0], [100.0, 100.0, 120.0, 120.0]],
                    "confidence": [0.9, 0.2],
                    "class_id": [0, 1],
                },
                {
                    "xyxy": [[1.0, 0.0, 21.0, 20.0], [101.0, 100.0, 121.0, 120.0]],
                    "confidence": [0.9, 0.2],
                    "class_id": [0, 1],
                },
            ],
        },
        {
            "name": "two_objects_output_order",
            "params": {"minimum_consecutive_frames": 1, "minimum_iou_threshold": 0.1},
            "frames": [
                {
                    "xyxy": [[0.0, 0.0, 20.0, 20.0], [100.0, 100.0, 120.0, 120.0]],
                    "confidence": [0.95, 0.95],
                    "class_id": [0, 1],
                },
                {
                    "xyxy": [[101.0, 100.0, 121.0, 120.0], [1.0, 0.0, 21.0, 20.0]],
                    "confidence": [0.95, 0.95],
                    "class_id": [1, 0],
                },
            ],
        },
        {
            "name": "ocr_recovers_short_gap",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold": 0.1,
                "lost_track_buffer": 5,
            },
            "frames": [
                {"xyxy": [[50.0, 50.0, 80.0, 80.0]], "confidence": [0.95]},
                {"xyxy": [[52.0, 50.0, 82.0, 80.0]], "confidence": [0.95]},
                {"xyxy": [], "confidence": []},
                {"xyxy": [[56.0, 50.0, 86.0, 80.0]], "confidence": [0.95]},
            ],
        },
    ]

    for case in cases:
        tracker = OCSORTTracker(**case["params"])
        tracker.reset()
        expected_ids = []
        expected_indices = []
        for frame in case["frames"]:
            result = tracker.update(_detections(frame))
            expected_ids.append([] if result.tracker_id is None else result.tracker_id.astype(int).tolist())
            expected_indices.append(_output_indices(frame, result))
        case["expected_tracker_id"] = expected_ids
        case["expected_output_indices"] = expected_indices
    _write("ocsort_cases.json", cases)


def generate_botsort_cases() -> None:
    cases: list[dict[str, Any]] = [
        {
            "name": "empty_frames",
            "params": {"minimum_consecutive_frames": 1, "enable_cmc": False},
            "frames": [{"xyxy": [], "confidence": []}, {"xyxy": [], "confidence": []}],
        },
        {
            "name": "single_object_instant_first_frame",
            "params": {"minimum_iou_threshold_first_assoc": 0.1, "enable_cmc": False},
            "frames": [
                {"xyxy": [[0.0, 0.0, 20.0, 20.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[1.0, 0.0, 21.0, 20.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[2.0, 0.0, 22.0, 20.0]], "confidence": [0.9], "class_id": [0]},
            ],
        },
        {
            "name": "unconfirmed_track_confirms_on_second_frame",
            "params": {
                "minimum_consecutive_frames": 2,
                "minimum_iou_threshold_unconfirmed_assoc": 0.1,
                "instant_first_frame_activation": False,
                "enable_cmc": False,
            },
            "frames": [
                {"xyxy": [[10.0, 10.0, 30.0, 30.0]], "confidence": [0.9], "class_id": [0]},
                {"xyxy": [[11.0, 10.0, 31.0, 30.0]], "confidence": [0.9], "class_id": [0]},
            ],
        },
        {
            "name": "missing_confidence_defaults_to_one",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold_first_assoc": 0.1,
                "enable_cmc": False,
            },
            "frames": [
                {"xyxy": [[10.0, 10.0, 30.0, 30.0]], "class_id": [0]},
                {"xyxy": [[11.0, 10.0, 31.0, 30.0]], "class_id": [0]},
            ],
        },
        {
            "name": "low_confidence_second_stage_recovery",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold_first_assoc": 0.1,
                "minimum_iou_threshold_second_assoc": 0.1,
                "track_activation_threshold": 0.5,
                "high_conf_det_threshold": 0.6,
                "enable_cmc": False,
            },
            "frames": [
                {"xyxy": [[0.0, 0.0, 50.0, 50.0]], "confidence": [0.9]},
                {"xyxy": [[2.0, 2.0, 52.0, 52.0]], "confidence": [0.3]},
            ],
        },
        {
            "name": "very_low_confidence_is_discarded",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold_first_assoc": 0.1,
                "track_activation_threshold": 0.5,
                "high_conf_det_threshold": 0.6,
                "enable_cmc": False,
            },
            "frames": [
                {"xyxy": [[0.0, 0.0, 20.0, 20.0]], "confidence": [0.9]},
                {"xyxy": [[1.0, 0.0, 21.0, 20.0]], "confidence": [0.05]},
            ],
        },
        {
            "name": "two_objects_output_order",
            "params": {
                "minimum_consecutive_frames": 1,
                "minimum_iou_threshold_first_assoc": 0.1,
                "enable_cmc": False,
            },
            "frames": [
                {
                    "xyxy": [[0.0, 0.0, 20.0, 20.0], [100.0, 100.0, 120.0, 120.0]],
                    "confidence": [0.95, 0.95],
                    "class_id": [0, 1],
                },
                {
                    "xyxy": [[101.0, 100.0, 121.0, 120.0], [1.0, 0.0, 21.0, 20.0]],
                    "confidence": [0.95, 0.95],
                    "class_id": [1, 0],
                },
            ],
        },
    ]

    for case in cases:
        tracker = BoTSORTTracker(**case["params"])
        tracker.reset()
        expected_ids = []
        expected_indices = []
        for frame in case["frames"]:
            result = tracker.update(_detections(frame))
            expected_ids.append([] if result.tracker_id is None else result.tracker_id.astype(int).tolist())
            expected_indices.append(_output_indices(frame, result))
        case["expected_tracker_id"] = expected_ids
        case["expected_output_indices"] = expected_indices
    _write("botsort_cases.json", cases)


def generate_manifest() -> None:
    import trackers

    _write(
        "manifest.json",
        {
            "python": f"{sys.version_info.major}.{sys.version_info.minor}",
            "numpy": np.__version__,
            "psutil": psutil.__version__,
            "scipy": scipy.__version__,
            "supervision": sv.__version__,
            "trackers": getattr(trackers, "__version__", "editable"),
            "policy": {
                "tracker_ids": "exact",
                "floats": {"atol": 1e-7, "rtol": 1e-7},
                "kalman_state": {"atol": 1e-9, "rtol": 1e-7},
            },
        },
    )


def main() -> None:
    generate_assignment_cases()
    generate_iou_cases()
    generate_kalman_case()
    generate_sort_cases()
    generate_bytetrack_cases()
    generate_ocsort_cases()
    generate_botsort_cases()
    generate_manifest()
    _write_dart_fixture_library()


if __name__ == "__main__":
    main()
